use_lockfile = false

[project]
name = "presentifyr"
r_version = "4.5"

repositories = [
	{ alias = "PRISM", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2026-07-16/" },
    { alias = "pyro", url = "https://prism.dev.a2-ai.cloud/rpkgs/fyrverse/v1" },
]

dependencies = [
    { name = "presentifyr", path = ".", install_suggestions = true },
    { name = "pyro", repository = "pyro" },
    "devtools",
]
